name = "minimal-nav"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "frontend/dist"

[[d1_databases]]
binding = "DB"
database_name = "minimal-nav-db"
database_id = "c6246e3b-bb49-41b4-b4d6-b872bd221e52"
